CREATE DATABASE RAGUTE;

USE RAGUTE;

CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    ATIVO BOOLEAN,
    EMAIL VARCHAR(50)
    IMG VARCHAR(80)
);

CREATE TABLE PRODUTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL,
    IMG VARCHAR(255) NOT NULL,
    ATIVO BOOLEAN NOT NULL,
    INGREDIENTES VARCHAR(255)
);


CREATE TABLE CATEGORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    ID_PRODUTOS INT
);

CREATE TABLE SUB_CAT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    ID_CATEGORIA INT
);


ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTOS
FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID);

ALTER TABLE SUB_CAT ADD CONSTRAINT FK_SUB_CAT_CATEGORIA
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID);