-- CRIANDO BANCO
CREATE DATABASE RAGUTE;

-- CONECTANDO NO BANCO
USE RAGUTE;

-- CRIANDO TABELA USUARIOS
CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

-- INSERINDO 1 USUARIO
INSERT INTO USUARIOS VALUES (NULL, 'admi', md5('rag@2022'));

-- CRIANDO TABELA PRODUTOS
CREATE TABLE PRODUTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL,
    INGREDIENTES VARCHAR(255),
    ATIVO BOOLEAN NOT NULL,
    IMG VARCHAR(255),
    ID_CATEGORIA INT
);

-- CRIANO TABELA INGREIENTES
CREATE TABLE INGREDIENTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INGREDIENTE VARCHAR(30)
);

-- CRIANDO TABELA DE RELACIONAMENTO NXM (INGREDIENTES, PRODUTOS)
CREATE TABLE CONTEM(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTOS INT NOT NULL,
    ID_INGREDIENTES INT NOT NULL,
    QUANTIDADE INT(10)
);

-- CRIANDO TABELA CATEGORIA
CREATE TABLE CATEGORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
);


-- ADICIONANDO FOREIGN KEYS
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_CATEGORIA
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID);

ALTER TABLE CONTEM ADD CONSTRAINT FK_CONTEM_PRODUTOS
FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID);

ALTER TABLE CONTEM ADD CONSTRAINT FK_CONTEM_INGREDIENTES
FOREIGN KEY (ID_INGREDIENTES) REFERENCES INGREDIENTES(ID);

-- INSERINDO CATEGORIAS
INSERT INTO CATEGORIA VALUES (NULL, 'Hamburguer');
INSERT INTO CATEGORIA VALUES (NULL, 'Artesanais');
INSERT INTO CATEGORIA VALUES (NULL, 'Frango');
INSERT INTO CATEGORIA VALUES (NULL, 'Hot-Dogs');
INSERT INTO CATEGORIA VALUES (NULL, 'Porções Quentes');
INSERT INTO CATEGORIA VALUES (NULL, 'Porções Frias');
INSERT INTO CATEGORIA VALUES (NULL, 'Não Alcoólicas');
INSERT INTO CATEGORIA VALUES (NULL, 'Alcoólicas');

-- INSERINDO INGREDIENTES
INSERT INTO INGREDIENTES VALUES (NULL, 'Hamburguer');
INSERT INTO INGREDIENTES VALUES (NULL, 'Alface');
INSERT INTO INGREDIENTES VALUES (NULL, 'Tomate');
INSERT INTO INGREDIENTES VALUES (NULL, 'Ovo');
INSERT INTO INGREDIENTES VALUES (NULL, 'Queijo');
INSERT INTO INGREDIENTES VALUES (NULL, 'Presunto');
INSERT INTO INGREDIENTES VALUES (NULL, 'Catupiry');
INSERT INTO INGREDIENTES VALUES (NULL, 'Bacon');
INSERT INTO INGREDIENTES VALUES (NULL, 'Cheddar');
INSERT INTO INGREDIENTES VALUES (NULL, 'Filé de Frango');
INSERT INTO INGREDIENTES VALUES (NULL, 'Hamburguer Caseiro');
INSERT INTO INGREDIENTES VALUES (NULL, 'Salsicha');