CREATE DATABASE RAGUTE;

USE RAGUTE;

CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL
);

INSERT INTO USUARIOS VALUES (NULL, 'admin', 'rag@2022');

CREATE TABLE PRODUTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL,
    INGREDIENTES VARCHAR(255),
    ATIVO BOOLEAN NOT NULL,
    IMG VARCHAR(255)
);

CREATE TABLE CATEGORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    ID_PRODUTOS INT
);

ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTOS
FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID);