CREATE DATABASE RAGUTE;

USE RAGUTE;

CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL
);

INSERT INTO USUARIOS VALUES (NULL, 'admi', 'rag@2022');

CREATE TABLE PRODUTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL,
    INGREDIENTES VARCHAR(255),
    ATIVO BOOLEAN NOT NULL,
    IMG VARCHAR(255)
);

CONSTRAINT TABLE INGREDIENTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
);

CREATE TABLE CONTEM(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTOS INT NOT NULL,
    ID_INGREDIENTES INT NOT NULL
);

CREATE TABLE CATEGORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    ID_PRODUTOS INT
);

ALTER TABLE INGREDIENTES ADD CONSTRAINT FK_INGREDIENTES_PRODUTOS
FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID);

ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTOS
FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID);

ALTER TABLE CONTEM ADD CONSTRAINT FK_CONTEM_PRODUTOS
FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID);

ALTER TABLE CONTEM ADD CONSTRAINT FK_CONTEM_INGREDIENTES
FOREIGN KEY (ID_INGREDIENTES) REFERENCES INGREDIENTES(ID);